version: '3.5'

networks:
  k6-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.0
    ports:
      - '8086:8086'

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
